# Generated by Django 3.0.4 on 2022-08-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('dob', models.DateField()),
                ('client_key', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('country', models.CharField(default='VN', max_length=256)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_dttm', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
    ]
